const countries = {
    India: ["Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"],
    Iran: ["Tehran", "Isfahan", "Fars", "Kerman", "Mazandaran", "Gilan", "Golestan", "Qom", "Qazvin", "Semnan", "Yazd", "Zanjan", "Hamadan", "Kurdistan", "Kermanshah", "Ilam", "Khuzestan", "Bushehr", "Hormozgan", "Sistan and Baluchestan", "North Khorasan", "Razavi Khorasan", "South Khorasan", "Ardabil", "East Azerbaijan", "West Azerbaijan", "Markazi", "Lorestan", "Chaharmahal and Bakhtiari", "Kohgiluyeh and Boyer-Ahmad", "Alborz"],
    USA: ["California", "Texas", "Florida", "New York", "Illinois", "Pennsylvania", "Ohio", "Georgia", "North Carolina", "Michigan", "New Jersey", "Virginia", "Washington", "Arizona", "Massachusetts"],
    China: ["Guangdong", "Beijing", "Shanghai", "Zhejiang", "Jiangsu", "Sichuan", "Shandong", "Henan", "Hubei", "Fujian", "Anhui", "Hebei", "Hunan", "Yunnan", "Tianjin"],
    Japan: ["Tokyo", "Osaka", "Kyoto", "Hokkaido", "Aichi", "Fukuoka", "Hyogo", "Hiroshima", "Miyagi", "Okinawa", "Saitama", "Chiba", "Kanagawa"],
    Germany: ["Bavaria", "Berlin", "Hamburg", "Hesse", "Saxony", "Brandenburg", "Bremen", "Lower Saxony", "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland", "Schleswig-Holstein", "Thuringia"],
    UK: ["England", "Scotland", "Wales", "Northern Ireland"],
    France: ["Île-de-France", "Provence-Alpes-Côte d’Azur", "Nouvelle-Aquitaine", "Occitanie", "Auvergne-Rhône-Alpes", "Normandy", "Brittany", "Corsica", "Grand Est", "Hauts-de-France"],
    Canada: ["Ontario", "Quebec", "British Columbia", "Alberta", "Manitoba", "Saskatchewan", "Nova Scotia", "New Brunswick", "Prince Edward Island", "Newfoundland and Labrador"],
    Argentina: ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán", "Salta", "Entre Ríos", "Chaco", "Misiones", "Neuquén"],
    Netherlands: ["North Holland", "South Holland", "Utrecht", "Gelderland", "North Brabant", "Limburg", "Zeeland", "Friesland", "Groningen", "Drenthe"],
    Switzerland: ["Zurich", "Bern", "Geneva", "Vaud", "Aargau", "Lucerne", "Ticino", "St. Gallen", "Basel-Stadt", "Valais"],
    Sweden: ["Stockholm", "Skåne", "Västra Götaland", "Uppsala", "Östergötland", "Jönköping", "Halland", "Dalarna", "Värmland", "Gävleborg"],
    Norway: ["Oslo", "Viken", "Vestland", "Rogaland", "Trøndelag", "Innlandet", "Agder", "Møre og Romsdal", "Nordland", "Troms og Finnmark"],
    NewZealand: ["Auckland", "Wellington", "Canterbury", "Waikato", "Otago", "Bay of Plenty", "Manawatū-Whanganui", "Northland", "Taranaki", "Hawke's Bay"],
    Egypt: ["Cairo", "Giza", "Alexandria", "Dakahlia", "Red Sea", "Beheira", "Faiyum", "Gharbia", "Ismailia", "Aswan"],
    Nigeria: ["Lagos", "Kano", "Rivers", "Kaduna", "Oyo", "Delta", "Edo", "Enugu", "Ogun", "Abia"],
    Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Chonburi", "Krabi", "Khon Kaen", "Surat Thani", "Nakhon Ratchasima", "Udon Thani", "Ayutthaya"],
    Vietnam: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hai Phong", "Can Tho", "Quang Ninh", "Thanh Hoa", "Nghe An", "Dong Nai", "Binh Duong"],
    Australia: ["New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania", "Northern Territory", "Australian Capital Territory"],
    Brazil: ["São Paulo", "Rio de Janeiro", "Bahia", "Paraná", "Pernambuco", "Ceará", "Amazonas", "Minas Gerais", "Pará", "Santa Catarina"],
    Russia: ["Moscow", "Saint Petersburg", "Tatarstan", "Krasnodar Krai", "Sverdlovsk Oblast", "Novosibirsk Oblast", "Rostov Oblast", "Chelyabinsk Oblast", "Samara Oblast", "Bashkortostan"],
    Italy: ["Lombardy", "Lazio", "Sicily", "Veneto", "Tuscany", "Piedmont", "Campania", "Emilia-Romagna", "Liguria", "Sardinia"],
    Spain: ["Madrid", "Catalonia", "Andalusia", "Valencia", "Galicia", "Basque Country", "Canary Islands", "Aragon", "Murcia", "Castile and León"],
    SouthKorea: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan", "Gyeonggi-do", "Gangwon-do", "Jeju-do"],
    Mexico: ["Mexico City", "Jalisco", "Nuevo León", "Puebla", "Guanajuato", "Chiapas", "Yucatán", "Veracruz", "Sonora", "Baja California"],
    Indonesia: ["Jakarta", "West Java", "Central Java", "East Java", "Bali", "North Sumatra", "South Sulawesi", "Banten", "Riau", "Aceh"],
    SaudiArabia: ["Riyadh", "Makkah", "Madinah", "Eastern Province", "Asir", "Tabuk", "Qassim", "Jazan", "Najran", "Al Bahah"],
    UAE: ["Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain"],
    Turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep", "Mersin", "Kayseri"],
    SouthAfrica: ["Gauteng", "Western Cape", "KwaZulu-Natal", "Eastern Cape", "Free State", "Limpopo", "Mpumalanga", "North West", "Northern Cape"]
}

export default countries;